name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Create config 
        run: |
          touch config.py
          echo "TARGET_YEAR = 2023" >> config.py
          echo "LICENSE_PREFIX = \\" >> config.py
          echo "\"\"\"MIT License" >> config.py
          echo "" >> config.py
          echo "Copyright (c) \"\"\"" >> config.py

      - name: Install pipenv and requirements
        run: |
          python -m pip install --upgrade pipenv wheel
          python -m pip install -r requirements.txt
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          
      - name: Run tests
        shell: bash
        run: |
          PYTHONPATH="$(pwd)" pytest test.py